### ISSUE TITLE
no leading "window."?

### ISSUE THREAD

**Issue by Pomax** [rluba/browserify-global-shim#2]
Is there a way to make the replacement code not use the leading `window.` so that resolution is based on whatever happens to be available, scoped?

**Comment by rluba** [comment]
No, that’s not possible at the moment. But it would be easy to add. Do you still need this feature?

**Comment by Pomax** [comment]
I don't personally, no idea whether anyone else might benefit from it (probably yes, but not enough to hit up github I guess)

**Comment by rluba** [comment]
OK, I’ll close it then until someone else needs it.
