### ISSUE TITLE
Dependency's dependency not shimmed

### ISSUE THREAD

**Issue by dlwalsh** [rluba/browserify-global-shim#3]
I'm using browerify-global-shim to shim React, which has worked great until now.

The problem I've encountered is in using react-chartify. I can see from the bundle that all my instances of React are assigned to window.React. However, the code from react-chartify still has React = require('react') even after the transformation.

Thus my web app now contains conflicts caused by having two instances of React.

How do I solve this?

**Comment by doublerebel** [comment]
I was looking for this also.  Just add `global: true` [to the opts arg of b.transform](https://github.com/substack/node-browserify#btransformtr-opts).

**Comment by alekbarszczewski** [comment]
:+1:
