### ISSUE TITLE
Transform is processing non-JS files; use includeExtensions transform tools option

### ISSUE THREAD

**Issue by cperryk** [rluba/browserify-global-shim#4]
I'm requiring CSS files and Mustache files using browserify-css and hoganify. I'm finding that browserify-global-shim does not play well with this because it is trying to process these files that aren't JS files. It leads to a `SyntaxError: Unexpected Token`.

To fix this, use the `includeExtensions` option that Browserify-transform-tools features. It limits the transform to files with one of the listed extensions. I was able to get around the bug by editing `browserify-global-shim.js` like so:

```
module.exports = transformTools.makeRequireTransform('browserify-global-shim',
	{
		evaluateArguments: true,
		includeExtensions: ['js'] // <-- PROCESS ONLY JS FILES
	},
	function(args, opts, cb) {
		var shimmedModules = opts.config || {};
// etc.
```

**Comment by cperryk** [comment]
Actually, `jsFilesOnly: true` might be better because it supports other JS-related extensions like .coffee.

**Comment by asiniy** [comment]
@cperryk it seems author forgot about this repo

**Comment by cperryk** [comment]
:'( I think exposify does the same thing https://github.com/thlorenz/exposify

**Comment by asiniy** [comment]
@cperryk I solved my problems with `debowerify`

**Comment by rluba** [comment]
@cperryk, @asiniy: You are right, I completely ignored this repo for a long time while being swamped with other work.

I just used this module once to set up the build process for [hamjest](https://github.com/rluba/hamjest) and then never touched it again.

Are you still using it?

**Comment by asiniy** [comment]
@rluba I found `debowerify` more helpful for me
